"""Build the Level 2 safety-module migration from scripts/data/safety_modules_l2.json.

Session 41: splits the single Phase 1 safety module into three (Safety I–III).
The JSON is the source of truth; re-run this after editing it, then apply with
  npx supabase db query --linked -f supabase/migrations/20260928120000_split_safety_modules_l2.sql
(not `db push` — see CLAUDE.md).

Usage: python scripts/build_safety_migration.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "scripts" / "data" / "safety_modules_l2.json"
OUT = ROOT / "supabase" / "migrations" / "20260928120000_split_safety_modules_l2.sql"

EXISTING_SAFETY_ID = "19247004-7cb2-4f6b-bb3c-16bde4e6ff7e"
TAG = "$sfty$"


def dollar(text: str) -> str:
    assert TAG not in text, "content contains the dollar-quote tag"
    return f"{TAG}{text}{TAG}"


def main() -> None:
    data = json.loads(SRC.read_text(encoding="utf-8"))
    modules = data["modules"]
    ids = [m["id"] for m in modules]
    new_ids = [i for i in ids if i != EXISTING_SAFETY_ID]

    out: list[str] = [
        "-- Session 41: split the Level 2 Phase 1 safety module into Safety I–III",
        "-- GENERATED by scripts/build_safety_migration.py from scripts/data/safety_modules_l2.json — edit the JSON, not this file.",
        "-- Content is original wording based on NFPA 70E (2018 ed.), OSHA 29 CFR 1910 and the NETA L2 outline (Safety A–I).",
        "",
        "begin;",
        "",
        "-- Make room: Phase 1 modules after the safety module move down two places.",
        "-- Guarded so re-running the migration doesn't shift them again.",
        "update public.roadmap_modules",
        "set order_in_phase = order_in_phase + 2",
        "where neta_level = 2 and phase = 1 and order_in_phase >= 3",
        f"  and not exists (select 1 from public.roadmap_modules where id = '{new_ids[0]}');",
        "",
    ]

    for m in modules:
        content = dollar(json.dumps(m["content"], ensure_ascii=False))
        out += [
            f"-- {m['title']}",
            "insert into public.roadmap_modules (",
            "  id, phase, phase_title, order_in_phase, title, description, domain, neta_reference,",
            "  estimated_minutes, total_questions, content_sections, is_published, passing_score,",
            "  neta_level, video_recommended",
            ") values (",
            f"  '{m['id']}', 1, 'Foundation', {m['order_in_phase']}, {dollar(m['title'])}, {dollar(m['description'])},",
            f"  'Safety', {dollar(m['neta_reference'])}, {m['estimated_minutes']}, {len(m['questions'])},",
            f"  {content}::jsonb, true, 80, 2, false",
            ")",
            "on conflict (id) do update set",
            "  order_in_phase = excluded.order_in_phase, title = excluded.title,",
            "  description = excluded.description, domain = excluded.domain,",
            "  neta_reference = excluded.neta_reference, estimated_minutes = excluded.estimated_minutes,",
            "  total_questions = excluded.total_questions, content_sections = excluded.content_sections;",
            "",
        ]

    id_list = ", ".join(f"'{i}'" for i in ids)
    out += [
        "-- Replace the safety quiz questions (old module had no answers, stats or child questions)",
        f"delete from public.questions where roadmap_module_id in ({id_list});",
        "",
        "insert into public.questions (",
        "  domain, subdomain, level, concept_type, difficulty, frequency_tier, question, options,",
        "  correct_answer, explanation, trap_pattern, source, question_type, roadmap_module_id",
        ") values",
    ]
    rows = []
    for m in modules:
        for q in m["questions"]:
            trap = dollar(q["trap_pattern"]) if q.get("trap_pattern") else "null"
            rows.append(
                "  ('safety-standards', "
                f"'{q['subdomain']}', 2, '{q['concept_type']}', {q['difficulty']}, {q['frequency_tier']}, "
                f"{dollar(q['question'])}, {dollar(json.dumps(q['options'], ensure_ascii=False))}::jsonb, "
                f"'{q['correct_answer']}', {dollar(q['explanation'])}, {trap}, 'generated', 'roadmap', '{m['id']}')"
            )
    out.append(",\n".join(rows) + ";")
    out += ["", "commit;", ""]

    OUT.write_text("\n".join(out), encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(modules)} modules, {len(rows)} questions")


if __name__ == "__main__":
    main()
